# numpy

In [8]:
#Import Numpy Library
import numpy as np
from numpy import random

In [2]:
#how to creat array
arr= np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim #dimension

2

In [4]:
arr.shape #shape

(2, 4)

In [5]:
type (arr)

numpy.ndarray

In [6]:
arr.data #memory location

# random number generator

In [11]:
x= random.randint(100)
x

47

In [12]:
x= random.randint(100)
x

array([0.17910624, 0.85375717, 0.91774535, 0.67573078, 0.88576818,
       0.17348225, 0.09843527, 0.35358276, 0.84597849, 0.42274389,
       0.08211632, 0.59247999, 0.3948732 , 0.82132892, 0.97388903,
       0.33014118, 0.95305943, 0.54060218, 0.20262613, 0.24015323,
       0.48804053, 0.77663793, 0.39891049, 0.82037481, 0.52782686,
       0.53021256, 0.56243855, 0.29377775, 0.02746384, 0.55885957,
       0.85727207, 0.34709074, 0.1901757 , 0.48933947, 0.26630333,
       0.59881534, 0.28544232, 0.95307144, 0.91808286, 0.34805101,
       0.95039135, 0.43314176, 0.82117822, 0.04360533, 0.32153475,
       0.39620096, 0.54592935, 0.55677056, 0.79476674, 0.77555608,
       0.50064653, 0.0504337 , 0.39937443, 0.92414659, 0.61773273,
       0.82520381, 0.796653  , 0.17663269, 0.52843554, 0.47917901,
       0.16406267, 0.0156692 , 0.68445496, 0.35437151, 0.80074052,
       0.97107309, 0.78745089, 0.97699665, 0.46073503, 0.23977887,
       0.19218584, 0.55082847, 0.14628449, 0.32435564, 0.92394

In [13]:
x= random.rand(10)
x

array([0.57290364, 0.55204064, 0.97154795, 0.99672788, 0.11036111,
       0.79429881, 0.7612849 , 0.36407133, 0.34553551, 0.76298561])

In [15]:
x= random.randint(100, size=(5,3)) #two dimensional array
x

array([[22, 70, 31],
       [94, 37, 77],
       [75, 98, 99],
       [53, 13, 54],
       [17, 69,  2]])

# array work

In [16]:
a= random.randint(7)
a

5

In [26]:
a= random.randint(10, size=(7))
print ("A=",a)
b= random.randint(10, size=(7))
print ("B=",b)
c=a+b
print ("c=",c)
d=a*b
print("d=",d)
e=a/b
print("e=",e)

A= [6 1 4 3 8 7 4]
B= [5 7 5 0 9 6 5]
c= [11  8  9  3 17 13  9]
d= [30  7 20  0 72 42 20]
e= [1.2        0.14285714 0.8               inf 0.88888889 1.16666667
 0.8       ]


C:\Users\Sap\AppData\Local\Temp\ipykernel_14028\149780678.py:9: RuntimeWarning: divide by zero encountered in true_divide
  e=a/b


In [22]:
a*b

array([36,  7,  6,  8, 35,  7,  0])

In [23]:
a+b

array([13,  8,  5,  6, 12,  8,  6])

# Metrix in numpy

In [29]:
a=np.matrix('1 2;3 4')
a

matrix([[1, 2],
        [3, 4]])

In [31]:
a=np.matrix('1 2 3;3 4 5;5 6 7')
a

matrix([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

# measurement of central tendency

In [37]:
arr =np.array([[1,2,3],[4,5,6],[6,7,8]])
arr



array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [38]:
np.min(arr)

1

In [39]:
np.max(arr)

8

In [40]:
np.mean(arr)

4.666666666666667

In [41]:
np.median(arr)

5.0